export const favoriteBreakers = [
    "What’s something new you’ve learned about yourself in the last three months?",
    "If you had to describe how you’re feeling right now as an amusement park ride, what ride are you on?",
    "How would you describe your communication style in three words?",
    "How do you recognize when you’re stressed?",
    "If you were coming out onto a stage, what would your entrance theme song be?",
    "If you could bring back a fashion trend, what would it be and why?",
    "If you could live in another historical period, would you? If so, which one?",
    "If you were reincarnated as an animal, what would you choose and why?",
    "What’s one thing you are unbeatable at?",
    "How would you spend your days if you had unlimited time and resources?",
    "How do you get motivated for difficult tasks?",
    "What’s something on your desk, a nearby wall, or out the window that cheers you up during the day?",
    "Do you have any mentors or people you look up to? Tell us about one of them.",
    "What fictional world or place would you like to visit?",
    "You’ve been teleported to the Middle Ages. How do you make a living there?",
    "Suppose you were going to be frozen tomorrow for a one-way 1,000-year interstellar voyage. What would you most want to communicate (and to whom) before you leave?",
    "If you could have an animal sidekick, what would it be? Why?",
    "What looks easy-peasy lemon squeezy but is actually difficult difficult lemon difficult?",
    "You’ve died, but instead of entering the afterlife, you’ve entered Earth 2.0. What are some things that make Earth 2.0 better?",
    "If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?",
    "A genie appears and grants you a wish for someone else in the world. Who and what do you make a wish for?",
    "If you had a magic button on your desk to bring you whatever you wanted, what would it summon?",
    "What’s the last thing you did for the first time?",
    "What smell, image, or sound triggers nostalgia for you?",
    "What’s one thing your parents or guardians constantly nagged you about?",
    "Tell us about a stranger you still remember. What made them memorable?",
    "What ice cream flavor sums up your personality today?",
    "You’ve been granted a one-way ticket to another country of your choice. Where are you going?",
    "What’s something you’ve drawn inspiration from recently?",
    "It’s your first day on the job as an evil villain. What’s the first piece of mischief you commit?",
    "If buying groceries were a game, what would one of the loading screen tips be?"
]

export const easyBreakers = [
    "What animal best represents you today and why?",
    "If you could have one superpower today, what would it be, and what would you use it for?",
    "What thing from nature, excluding animals, best describes you today?",
    "If you had to sing karaoke right now, which song would you pick?",
    "What is the most used emoji on your phone right now?",
    "What was the first thing you thought about when you woke up today?",
    "Which do you prefer, oceans or mountains? Why?",
    "What’s one of your favorite recent memories?",
    "What’s the best phrase or piece of slang people in your hometown use?",
    "What’s your guilty pleasure right now?",
    "What book would you like to live in?",
    "If you could be famous for one thing, what would it be?",
    "What’s a word or phrase in another language (or your own) that you really like?",
    "What’s the best topping for ice cream?",
    "If you’re at trivia night, what would category would you know most about?",
    "What’s an album you recommend that has no bad songs?",
    "What’s the worst haircut you ever had?",
    "What’s your most successful dance move? Do you dare show it?",
    "What’s an obscure TV show or movie that everyone should watch?"
]

export const funnyBreakers = [
    "What’s the weirdest thing in your fridge right now?",
    "If you were setting off to Mars and could take only one luxury item with you, what would it be?",
    "If you could become a supernatural creature at night, what would it be, and why?",
    "Which fictional character would you want by your side during a zombie apocalypse?",
    "If you were a cocktail, which one would you be?",
    "If your home was packed full of golf balls, how would you remove them?",
    "Would you rather talk like Yoda or breathe like Darth Vader?",
    "Would you rather speak all languages or be able to talk with animals?",
    "What would you do if you came home and found a penguin in your freezer?",
    "What takeaway food represents you today and why?",
    "If you could invent a holiday, what would it be, and what would you call it?",
    "If your car had vanity plates, what would they say?",
    "What is the best bird?",
    "Do you have a favorite dinosaur?",
    "You’ve been chosen to represent your country in a global competition. What sport or activity are you doing?"
]

export const workBreakers = [
    "If you had to describe how you’re feeling right now as a weather pattern, what’s your forecast?",
    "What’s an under-rated skill everyone can benefit from?",
    "What’s something you’re worried about (professionally)?",
    "What’s got your attention today and why?",
    "What was your favorite recent book or article, and what did it inspire?",
    "Heard any good tips lately?",
    "What color best describes your personality today?",
    "What’s one project you could stop doing to give yourself more focus?",
    "What are you excited about this week?",
    "Do you have any routines you use to improve your energy and focus?",
    "What’s one thing you wish could be automated in your job?",
    "What’s one thing you’ve been procrastinating on and can’t finish?",
    "What’s the last thing you completed that you’re proud of?",
    "Have you learned any useful productivity hacks recently?",
    "What’s one productivity tool you couldn’t live without, and what makes it indispensable?",
    "What’s one recent thing or experience that exceeded your expectations?",
    "What are you grateful for today?",
    "What’s something that made you smile recently?",
    "What fruit or vegetable represents your mood today?",
    "What small thing would improve your day today?",
    "What’s something that puts you in a state of flow?",
    "What’s one possession or tool that enhances your daily life?",
    "What’s a simple life hack that everyone can benefit from?",
    "What’s one of the best ideas our company has come up with?",
    "What’s something you want to get better at?",
    "What’s your favorite song or soundtrack for doing focused work?"
]